### ISSUE TITLE
Misleading project name?

### ISSUE THREAD

**Issue by ypid** [adithyakhamithkar/ansible#3]
Hi

I found your project on [CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/167) and at first thought that this was [the Ansible project](https://www.ansible.com/) until I read the description. Naming is difficult we all know that but using (just) Ansible is misleading.

**Comment by adithyakhamithkar** [comment]
Hi,

Thanks for the feedback i'll look for an alternative name.

**Comment by ypid** [comment]
Thanks! Maybe you can reopen so that others may find the issue and can propose alternative names?

**Comment by adithyakhamithkar** [comment]
Renamed to http://adithyakhamithkar.github.io/ansible-playbooks
