### ISSUE TITLE
Can’t find basic documentation which is claimed to exist.

### ISSUE THREAD

**Issue by ypid** [adithyakhamithkar/ansible#4]
I am referring to [CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/167) under Documentation. Maybe you can add a URL as recommended by the CII to make it easier for outsides to find it?

Edit: I guess you are referring to https://adithyakhamithkar.github.io/ansible/ I might be a bit spoiled with http://docs.debops.org/ :wink: But as an outside, I don’t think that the basic documentation criteria of is currently met …

**Comment by adithyakhamithkar** [comment]
I have tried to keep the documentation for a few playbooks
https://github.com/adithyakhamithkar/ansible/tree/master/AWS/roles/create-iam-read-only-group
https://github.com/adithyakhamithkar/ansible/tree/master/AWS/roles/create-iam-policy
https://github.com/adithyakhamithkar/ansible/tree/master/roles/kafka-manager

There are more and they can be found.
https://github.com/adithyakhamithkar/ansible/blob/master/README.md

**Comment by ypid** [comment]
Thanks for the hint. Related to #5.
