### ISSUE TITLE
CII Best Practices: Static code analysis

### ISSUE THREAD

**Issue by ypid** [adithyakhamithkar/ansible#5]
Hi

I am going though the [CII Best Practices](https://bestpractices.coreinfrastructure.org) criteria for the [DebOps Project](http://debops.org/) and I found your project (edit: has been deleted from https://bestpractices.coreinfrastructure.org/, ID [167](https://bestpractices.coreinfrastructure.org/projects/167) 2 hours after reporting this issue) to be similar so I am peeking a bit. But I am unsure how serious you did go thought the criteria. You state that https://github.com/adithyakhamithkar/ansible uses static code analysis but I am not aware of any existing tool for Ansible. Can you maybe add a reference?

Related to: https://github.com/debops/debops/issues/154

**Comment by ypid** [comment]
Also, you state that you have https://reproducible-builds.org/ Do you publish VM templates which are build reproducible? I would be quite interested in that …

**Comment by adithyakhamithkar** [comment]
I started this repo just as a hobby of writing playbooks, my objective of signing of up for CII was to evaluate my best practices.

I see that the standards are too high when i look at Debops. But i will work on it and try to keep up.

Keeping this in mind I have deleted my project from CII Best Practices as I understand that I still have a long way to go.

**Comment by ypid** [comment]
> I started this repo just as a hobby of writing playbooks, my objective of signing of up for CII was to evaluate my best practices.

That is also how I started with Ansible and the reason for debops/debops#154 :smile: No problem with that.

> Keeping this in mind I have deleted my project from CII Best Practices as I understand that I still have a long way to go.

That was not my indention. The CII Best Practices are meant to help improving FLOSS projects so the CII Best Practices are a good companion in your journey. It is not expected that projects meet all the criteria from the beginning. Refer to [OpenSSL before Heartbleed](https://bestpractices.coreinfrastructure.org/projects/87). Maybe when you have time, you can go thought the criteria again.

**Comment by adithyakhamithkar** [comment]
I am a sole contributor to this I would not be able to reach that level of best practices alone.

**Comment by ypid** [comment]
Have you looked into the DebOps project yet? We also have work to do to reach this level of best practices :wink:

**Comment by adithyakhamithkar** [comment]
I did have a brief look at it. I would need a guide or a few like minded friends to follow them, It's not easy to reach that level.
